# Rustfmt configuration for consistent code formatting

# Basic formatting
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

# Functions and structs
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
trailing_comma = "Vertical"
trailing_semicolon = true

# Comments
wrap_comments = true
comment_width = 80
normalize_comments = true

# Strings
format_strings = true
format_code_in_doc_comments = true

# Misc
use_field_init_shorthand = true
use_try_shorthand = true
force_explicit_abi = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false
